apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  # NODE_ENV: "production"
  NODE_ENV: "development"
  LOG_LEVEL: "info"
  GATEWAY_PORT: "3000"
  # Gateway backend URLs (cluster-internal DNS)
  AUTH_SERVICE_URL: "http://auth-service:3001"
  USER_SERVICE_URL: "http://user-service:3002"
  PRODUCT_SERVICE_URL: "http://product-service:3003"
  ORDER_SERVICE_URL: "http://order-service:3004"
  # Auth service
  PORT: "3001"
  SERVICE_NAME: "auth-service"
  # User service
  USER_SERVICE_PORT: "3002"
  # Product service
  PRODUCT_SERVICE_PORT: "3003"
  # Order service (also needs USER_SERVICE_URL, PRODUCT_SERVICE_URL, RABBITMQ_URL from secret)
  ORDER_SERVICE_PORT: "3004"
  # Payment service
  PAYMENT_SERVICE_PORT: "3005"
  # Notification service
  NOTIFICATION_SERVICE_PORT: "3006"
