apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecommerce
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres-auth-db.yaml
  - postgres-user-db.yaml
  - postgres-product-db.yaml
  - postgres-order-db.yaml
  - postgres-payment-db.yaml
  - postgres-notification-db.yaml
  - rabbitmq.yaml
  - gateway.yaml
  - auth-service.yaml
  - user-service.yaml
  - product-service.yaml
  - order-service.yaml
  - payment-service.yaml
  - notification-service.yaml
  - ingress.yaml
